{% set name = "fd" %}
{% set version = "8.43.7" %}

package:
   name: "{{ name }}"
   version: "{{ version }}"

source:
   url: http://software.igwn.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
   sha256: 53326be8e16aa64d87d48da9016567e24104d027477cc098caa22e5e060ab925

build:
  run_exports:
    - {{ pin_subpackage("fd", max_pin="x") }}
  error_overdepending: true
  error_overlinking: true
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - ninja
    - make  # [unix]
    - pkg-config  # [unix]
  host:
    - cfg >=10.5.2
    - cm >=10.3.4
    - frv >=4.36
    - libframel >=8.42.1

test:
  requires:
    - pkg-config
  commands:
    - test -x ${PREFIX}/bin/FdGetChannelsList  # [unix]
    - test -x ${PREFIX}/bin/FdGetFramesInMemory  # [unix]
    - test -x ${PREFIX}/bin/FdIOServer  # [unix]
    - test -x ${PREFIX}/bin/FdMoni  # [unix]
    - test -x ${PREFIX}/bin/FdRangeGating  # [unix]
    - test -x ${PREFIX}/bin/FdSend  # [unix]
    - test -x ${PREFIX}/bin/FdStat  # [unix]
    - test -x ${PREFIX}/bin/FdWrite  # [unix]
    - test -r ${PREFIX}/lib/libfd.so  # [unix]
    - test -f ${PREFIX}/include/fd/Fd.h  # [unix]
    - pkg-config --print-errors --exact-version "{{ version }}" fd

about:
  home: "https://git.ligo.org/virgo/virgoapp/Cfg"
  license: "LGPL-2.1-or-later"
  license_family: GPL
  license_file: LICENSE
  summary: "Frame distribution library"
  description: |
    The Fd software has evolved from its early use in the Virgo DAQ system of transporting frames  
    over the network using the Cm package to a more general I/O framework for online and offline      
    applications. Its main purpose is to provide data in the frame format from and to files, shared
    memory and network connection. Basic data conditioning tools like channel filtering, resampling
    are now included in Fd as well as frame manipulation like channels selection, frame resizing,
    trend frame building and frame merging between different streams. The frames handled by the Fd
    package could contain any frame structures, from time series to events.

extra:
  recipe-maintainers:
      - rhyspoulton
      - fcarbogn 
